title: Rose Gogliotti # your name (or website title) here
logo: "/images/headshot.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  M
  <br><br>
  I am a professional problem finder. As a client-facing analytical consultant with more than a decade of experience in the nuclear industry, I understand the importance of things being done correctly. I have made a career at being very good at finding and solving problems before they cause real damage.
  <br><br>
  I am currently a consultant with SC&A Inc., an environmental and energy consulting firm. In general, I provide health physics and applied statistical services to government clients (CDC, EPA, DOE, DHS)
  <br><br>
  <a href="www.linkedin.com/in/rgogliotti">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-D16ZLR8D94 # your Google Analytics tracking ID here
