title: Rose Gogliotti # your name (or website title) here
logo: "/images/headshot.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/rgogliotti/">LinkedIn</a> |
  <a href="https://github.com/rgogliotti">GitHub</a>
  </p>


  <br><br>
  M.S. Data Scientist
  <br><br>
  I am a professional problem finder. 
  <br><br>
  I am currently a consultant with SC&A Inc., an environmental and energy consulting firm. 
  <br><br>

  
theme: jekyll-theme-minimal
google_analytics: G-D16ZLR8D94 # your Google Analytics tracking ID here
